### ISSUE TITLE
fails to install legacy Whatsapp

### ISSUE THREAD

**Issue by dtiziano** [mukulkadel/mwatoi#11]
on EMUI  9.1.0 it fails to install the legacy whatsapp.
 "verify app USB" is disabled

when running the code at lines 52-54 in main.py
`print('Installing WhatsApp 2.11.431.')
 os.system('bin\\adb.exe install -d -r bin\\LegacyWhatsApp.apk')
 print('Installation complete!')`

the following error is thrown in adb.exe, but this is not catched by main.py and does not stop it from to continuuing
adb: failed to install bin\LegacyWhatsApp.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]

it results that when main.py tries to copy the data (line 79)
` shutil.copyfile('tmp\\apps\\com.whatsapp\\db\\msgstore.db','out\\android.db')`
the source location is not found, throwing the following error:
`Traceback (most recent call last):
  File "C:\Users\Tiziano\Downloads\mwatoi-master\mwatoi-master\main.py", line 79, in <module>
    shutil.copyfile('tmp\\apps\\com.whatsapp\\db\\msgstore.db','out\\android.db')
  File "C:\Users\Tiziano\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\apps\\com.whatsapp\\db\\msgstore.db'`

here attached the complete cmd output:
`C:\Users\Tiziano\Downloads\mwatoi-master\mwatoi-master>python main.py

WhatsApp android to ios transferrer

Please connect your Android device with USB Debugging enabled:
cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: No connection could be made because the target machine actively refused it. (10061)
* daemon not running; starting now at tcp:5037
* daemon started successfully

Android device connected!

***********************************************
Please backup all your whatsapp chats before proceeding.
***********************************************

Do you want to continue?[y/n]: y

Starting backup process.
Creating tmp directory.
Uninstalling current apk.
Success
Installing WhatsApp 2.11.431.
Performing Streamed Install
adb: failed to install bin\LegacyWhatsApp.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
Installation complete!
Backing up data.

Note: Please don't enter any password.

WARNING: adb backup is deprecated and may be removed in a future release
Now unlock your device and confirm the backup operation...
Extracting tmp\whatsapp.ab file.
Creating out directory.
Copying android db
Traceback (most recent call last):
  File "C:\Users\Tiziano\Downloads\mwatoi-master\mwatoi-master\main.py", line 79, in <module>
    shutil.copyfile('tmp\\apps\\com.whatsapp\\db\\msgstore.db','out\\android.db')
  File "C:\Users\Tiziano\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\apps\\com.whatsapp\\db\\msgstore.db'`

**Comment by dtiziano** [comment]
tried the same as above on samsung with Android 6.0.1
The installation of Whatsapp Legacy works.
But when main.py tries to copy the data (line 79)
`shutil.copyfile('tmp\\apps\\com.whatsapp\\db\\msgstore.db','out\\android.db')`
it still fails, returning 
`No such file or directory: 'tmp\\apps\\com.whatsapp\\db\\msgstore.db'`

**Comment by dtiziano** [comment]
as explained [here](https://github.com/MarcoG3/WhatsDump/issues/72) we need a newer apk version.
substituted the apk as in the link.

**Comment by dtiziano** [comment]
Close by #12

**Comment by spydafx** [comment]
hello, can you please explain how do i basically do the fix? i also have the msgstore error but im not that great at android and stuff so i could really use some help

**Comment by dtiziano** [comment]
Have a look at the infos in the updated readme in my pull request, I explain every step
_____________________
Tiziano Di Pietro
Eidg. Dipl. Masch. Ing. ETH

**Comment by dtiziano** [comment]
https://github.com/dtiziano/mwatoi/tree/c1be20b70380c42e573a7359f560de2135428472

**Comment by spydafx** [comment]
im stuck at step 7 i dont understand, i cant do bin command in the terminal (cmd in windows)

**Comment by dtiziano** [comment]
If on windows, of course bin\adb.exe ...
_____________________
Tiziano Di Pietro
Eidg. Dipl. Masch. Ing. ETH

via ca’ di sopra 10
CH-6597 Agarone

***@***.***
+41 75 414 48 80

**Comment by spydafx** [comment]
C:\Users\pc2\Desktop\mwatoi-master\bin>adb.exe pull -a /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Databases/msgstore.db.crypt14
adb: error: failed to get feature set: more than one device/emulator

**Comment by dtiziano** [comment]
If your android phone is connected, disconnect it from the computer. If not, then you have more than one local emulator running.
