### ISSUE TITLE
Unofficial Whatsapp Versions

### ISSUE THREAD

**Issue by 5tsuki** [mukulkadel/mwatoi#13]
Does this work on unofficial WhatsApp mods, such as _FMWhatsapp_, _GBWhatsapp_ or similar? or is there any sideloadable `.ipa` that can do something like Android to iOS migration?

**Comment by mukulkadel** [comment]
I don't think it'll work, but if you have any apk, can you please share them. I'll test them out and will try to add support for them also.

**Comment by 5tsuki** [comment]
Thank you very much for the quick response!
Here's a link to get FMWhatsapp, the one that I am using.
https://apk-download.co/V930/Fouad.Whats9.30_By_FouadMODS.apk
Would love to see it working, if there's anything I can help with, I'll be happy to help.

**Comment by 5tsuki** [comment]
Hi, I was able to transfer chats from Android `FMWhatsapp` to iOS `Stock`, I'll update the README with a PR explaining what I had done to get it working!
