### ISSUE TITLE
 No such file or directory: 'tmp\\apps\\com.whatsapp\\db\\msgstore.db'

### ISSUE THREAD

**Issue by Vitorbnc** [mukulkadel/mwatoi#9]
Hi,
I am trying to backup Whatsapp data from a Sony Xperia XZ Premium (G8142) running Android 9.0 and I am getting this error:
![image](https://user-images.githubusercontent.com/7032355/165847825-39cb4c18-0e46-446d-a378-0ae7ce25c579.png)

**Comment by mukulkadel** [comment]
Do you have any security enabled for the whatsapp? It seems like adb is not able to install the required whatsapp version.

**Comment by Vitorbnc** [comment]
Apparently newer Android versions won't let you install the APK if it is a downgrade. I believe an extra phone reboot is required.
I managed to do it using an external tool [WhatsApp-Key-DB-Extractor](https://forum.xda-developers.com/t/tool-whatsapp-key-db-extractor-crypt6-12-non-root-updated-october-2016.2770982/page-29#post-81902381).

In the end everything worked and apparently most (if not all) messages were restored. Thank you for the initiative, you are brilliant! 

I will fork this to keep a note of this alternative workflow and close this issue.
